image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install npm@latest -g && npm install --prefix=www www && wasm-pack build
    command: npm --prefix=www run start

ports:
  - port: 8080
    onOpen: open-preview